### ISSUE TITLE
Question on subdomains/multiple sites

### ISSUE THREAD

**Issue by animosity022** [enum-gg/caddy-discord#2]
I was trying to give this a whirl to replace my existing oAuth2 setup for something a bit more simplistic, but couldn't quite get the multiple sites working.

I followed along and go the auth portion setup and did something like:

```
        discord {
                client_id myid
                client_secret mysecret
                redirect https://auth.domain.com/discord/callback # Route you've configured with `discordauth callback`

                realm clique {
                        user "Myuser#1234"
                }
        }
```

I setup my auth like:

```
auth.domain.com {
        tls {
                dns cloudflare {env.CLOUDFLARE_API_TOKEN}
                resolvers 1.1.1.1
        }
        route /discord/callback {
                # Desigate route as OAuth callback endpoint
                discord callback
        }

        respond "Hello, world!"
}
```

and that seemed to work fine as I get the prompts to auth via Discord.

I have other sites though that look like:

```
pihole.domain.com {
        tls {
                dns cloudflare {env.CLOUDFLARE_API_TOKEN}
                resolvers 1.1.1.1
        }
        reverse_proxy 192.168.1.25:80
        encode zstd gzip
        protect using clique
}

```

When I hit that for example, it just redirects me back to the auth hello world and I'm not quite sure why. Is there a different way I should be using it with the other sites as that's my general use case.

auth - my auth site

apps/pihole/etc - my other sites that I want to sit behind Discord's Auth.

Hopefully that makes sense as this look very neat as I'm sure i'm just missing something.

**Comment by VeryStrongFingers** [comment]
This has been resolved since https://github.com/enum-gg/caddy-discord/releases/tag/v1.1.0 :)
