### ISSUE TITLE
Abandoned repo, do not use.

### ISSUE THREAD

**Issue by DJTOMATO** [enum-gg/caddy-discord#4]
Hi Just implemented this any loved it so far.

My issue is mainly that if the user is part of the realm, the check goes fine, and no issues there
but if the user is not part of the realm, the discord oauth screen keeps booting itself over and over and over, until you get limited by cloudflare.

I'd love to be able to catch a 401 or redirect to another page in case the user is not authenticated

but  ``respond "unauthorized`` just do nothing, as it still remains on discord oauth screen.

what can i do about this?

```        route /check/callback {
        # Desigate route as OAuth callback endpoint
                discord callback
        }

        route {
                # Player endpoint
                # Only allow discord users that auth against 'guild_checker' realm
                protect using guild_checker
                reverse_proxy 127.0.0.1:34801
                respond "test"
        }

        route /p2* {
                # Multiplayer endpoint
                # Only allow discord users that auth against 'guild_checker' realm
                protect using guild_checker
                reverse_proxy 127.0.0.1:34802

        }
        respond "Welcome to nothing"
```

Sorry and thanks in advance

Edit: Dev abandoned the code. don't bother trying this

**Comment by VeryStrongFingers** [comment]
It's not abandoned, just had other priorities 😆 this issue has been fixed with https://github.com/enum-gg/caddy-discord/commit/8886d2c635c3ee779ad44006977b277b8ccaeb5b
will be included in next version tag
