### ISSUE TITLE
Guild + role checks don't work, allowing even if specified

### ISSUE THREAD

**Issue by zuedev** [enum-gg/caddy-discord#8]
**Working:** (Shows 401 as expected)
```yaml
realm zuedev {
  user 723361818940276736 # zuedev
}
```

**Not working:** (Instead of showing 401, it's allowing access.)
```yaml
realm bluelock {
  guild 726545668667342910 { # unnamed group
    role 1201602415925928026 # blue lock
  }
}
```

**Comment by VeryStrongFingers** [comment]
@zuedev which version (or commit hash) was this happening with?

**Comment by zuedev** [comment]
9922ab5

Build config for ref:

<img width="360" alt="image" src="https://github.com/enum-gg/caddy-discord/assets/24614929/f89e4462-6ec8-4378-b5c5-f081c8bc7754">

**Comment by VeryStrongFingers** [comment]
https://github.com/enum-gg/caddy-discord/releases/tag/v1.2.0 should resolve the issues.
Can you update your docker file to `github.com/enum-gg/caddy-discord@v1.2.0` and try again?

**Comment by zuedev** [comment]
Confirmed working, thanks!
